webapp:
  build: .
  volumes:
    - "./:/src/"
  links:
    - "db"
  command: sh ./wait-for-pg.sh db npm run test

db:
  image: mdillon/postgis
  environment:
    POSTGRES_USER: "williamhuang"
    POSTGRES_DB: "middleman"
