DROP SCHEMA IF EXISTS m_pub CASCADE;
DROP SCHEMA IF EXISTS m_priv CASCADE;
DROP SCHEMA IF EXISTS postgraphile_watch CASCADE;

DROP ROLE IF EXISTS m_user;
DROP ROLE IF EXISTS m_visitor;
DROP ROLE IF EXISTS m_admin;
